
[[audits.windows-sys]]
who = "Linus Färnstrand <linus@mullvad.net>"
criteria = "safe-to-deploy"
version = "0.48.0"
notes = "This is just a test audit to explore cargo-vet. DO NOT TRUST THIS AUDIT"
aggregated-from = "https://raw.githubusercontent.com/mullvad/udp-over-tcp/add-cargo-vet-vetting/supply-chain/audits.toml"
